### ISSUE TITLE
chown: cannot access '/var/run/zm': No such file or directory

### ISSUE THREAD

**Issue by ycodryn** [bkjaya2020/bkjaya1952-docker-zoneminder-master-mysql8-#1]
Trying to use with docker build
#11 0.257 Adding user `www-data' to group `video' ...
#11 0.259 Adding user www-data to group video
#11 0.265 Done.
#11 0.335 Module cgi already enabled
#11 0.362 Enabling conf zoneminder.
#11 0.365 To activate the new configuration, you need to run:
#11 0.365   service apache2 reload
#11 0.394 Module rewrite already enabled
#11 0.421 Enabling module headers.
#11 0.424 To activate the new configuration, you need to run:
#11 0.424   service apache2 restart
#11 0.453 Enabling module expires.
#11 0.456 To activate the new configuration, you need to run:
#11 0.456   service apache2 restart
#11 0.459 chown: cannot access '/var/run/zm': No such file or directory

**Comment by bkjaya2020** [comment]
I think ,It should be
chmod 777 /var/run/zm . Plese see the docker file .

**Comment by bkjaya2020** [comment]
Can you show the Dockerfile that you have used ? I have downloaded my Code and re run the Docker build . But didn't come across your error please see the link for the details of the build 

https://app.box.com/s/fbqd52fezk99u4ydqw35drd5h66ymc8g

**Comment by ycodryn** [comment]
Hey. I`m using your exact Dockerfile (https://github.com/bkjaya2020/bkjaya1952-docker-zoneminder-master-mysql8-/blob/update-4-1-2021/Dockerfile) with cmd like any other container: docker build --tag zoneminder:latest .  Here is a screenshot: https://ibb.co/rwBNkGP

**Comment by bkjaya2020** [comment]
I can't see such  errors in my build . You should be careful about typo in the Dockerfile. I
have  recorded  the building process and given the link of the file below
for you to examine and find any deviation .
https://www.dropbox.com/s/6ewo8wxcgcuczmk/vokoscreenNG-2021-01-11_10-24-13.mkv?dl=0

**Comment by ycodryn** [comment]
Sure thing, thank you.
